# Generated by Django 5.2.3 on 2025-07-19 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gw2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('waypoint', models.CharField(blank=True, max_length=200)),
                ('map_name', models.CharField(blank=True, max_length=200)),
                ('guide', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gw2.item')),
            ],
        ),
    ]
