# Generated by Django 5.2.3 on 2025-07-19 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_homestead', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cat',
            options={'verbose_name': 'chat', 'verbose_name_plural': 'chats'},
        ),
    ]
