# Generated by Django 5.2.3 on 2025-07-19 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2', '0005_currency_source'),
        ('gw2_homestead', '0002_alter_cat_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gw2.currency')),
            ],
        ),
        migrations.CreateModel(
            name='NodeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gw2.source')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gw2.item')),
                ('costs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gw2_homestead.nodecost')),
                ('sources', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gw2_homestead.nodesource')),
            ],
        ),
    ]
