# Generated by Django 5.2.3 on 2025-07-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_homestead', '0003_nodecost_nodesource_node'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='costs',
        ),
        migrations.RemoveField(
            model_name='node',
            name='sources',
        ),
        migrations.AddField(
            model_name='node',
            name='costs',
            field=models.ManyToManyField(blank=True, to='gw2_homestead.nodecost'),
        ),
        migrations.AddField(
            model_name='node',
            name='sources',
            field=models.ManyToManyField(blank=True, to='gw2_homestead.nodesource'),
        ),
    ]
