# Generated by Django 5.2.3 on 2025-07-19 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_homestead', '0004_remove_node_costs_remove_node_sources_node_costs_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='node',
            options={'verbose_name': 'zone de récoltes', 'verbose_name_plural': 'zones de récoltes'},
        ),
    ]
