# Generated by Django 5.2.3 on 2025-07-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_homestead', '0005_alter_node_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='icon',
            field=models.URLField(blank=True),
        ),
    ]
