# Generated by Django 5.2.3 on 2025-07-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('rarity', models.CharField(blank=True, choices=[('Junk', 'Junk'), ('Basic', 'Basic'), ('Fine', 'Fine'), ('Masterwork', 'Masterwork'), ('Rare', 'Rare'), ('Exotic', 'Exotic'), ('Ascended', 'Ascended'), ('Legendary', 'Legendary')], max_length=10)),
                ('icon', models.URLField(blank=True)),
                ('data', models.JSONField(blank=True)),
            ],
        ),
    ]
