# Generated by Django 5.2.3 on 2025-07-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='rarity',
            field=models.CharField(blank=True, choices=[('Junk', '_Junk'), ('Basic', 'Basique'), ('Fine', 'Bien'), ('Masterwork', 'Maître'), ('Rare', 'Rare'), ('Exotic', 'Exo'), ('Ascended', 'Élevé'), ('Legendary', 'Légendaire')], max_length=10),
        ),
    ]
