# Generated by Django 5.2.3 on 2025-07-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2', '0002_alter_item_rarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='rarity',
            field=models.CharField(blank=True, choices=[('Junk', 'Inutile (gris)'), ('Basic', 'Basique (blanc)'), ('Fine', 'Raffiné (bleu)'), ('Masterwork', "Chef-d'œuvre (vert)"), ('Rare', 'Rare (jaune)'), ('Exotic', 'Exotique (orange)'), ('Ascended', 'Élevé (rose)'), ('Legendary', 'Légendaire (violet)')], max_length=10),
        ),
    ]
