# Generated by Django 5.2.3 on 2025-07-19 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gw2', '0003_alter_item_rarity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'objet', 'verbose_name_plural': 'objets'},
        ),
    ]
