# Generated by Django 5.2.3 on 2025-07-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2', '0005_currency_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'monnaie', 'verbose_name_plural': 'monnaies'},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'verbose_name': 'source', 'verbose_name_plural': 'sources'},
        ),
        migrations.AlterField(
            model_name='currency',
            name='data',
            field=models.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='item',
            name='data',
            field=models.JSONField(blank=True, default={}),
        ),
    ]
