# Generated by Django 5.2.3 on 2025-07-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2', '0006_alter_currency_options_alter_source_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
