# Generated by Django 5.2.3 on 2025-08-04 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gw2', '0008_alter_item_data'),
        ('lbm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decoration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upgrade_id', models.PositiveIntegerField(unique=True)),
                ('recipe_id', models.PositiveIntegerField()),
                ('name', models.CharField(blank=True, max_length=200)),
                ('icon', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gw2.item')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lbm.media')),
            ],
            options={
                'verbose_name': 'décoration',
                'verbose_name_plural': 'décorations',
            },
        ),
    ]
