# Generated by Django 5.2.3 on 2025-08-04 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_guild', '0001_initial'),
        ('lbm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decoration',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lbm.media'),
        ),
        migrations.AlterField(
            model_name='decoration',
            name='recipe_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
