# Generated by Django 5.2.3 on 2025-08-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_guild', '0002_alter_decoration_media_alter_decoration_recipe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decoration',
            name='icon',
            field=models.URLField(blank=True, help_text="Renseigné automatiquement depuis l'API si upgrade id existant"),
        ),
        migrations.AlterField(
            model_name='decoration',
            name='name',
            field=models.CharField(blank=True, help_text="Renseigné automatiquement depuis l'API si upgrade id existant", max_length=200),
        ),
    ]
