# Generated by Django 4.2.23 on 2025-09-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='period',
            field=models.CharField(blank=True, choices=[('daily', 'Quotidienne'), ('weekly', 'Hebdomadaire'), ('custom', 'Objectif')], max_length=10, verbose_name='Période'),
        ),
    ]
