# Generated by Django 4.2.23 on 2025-09-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_task', '0003_alter_task_end_date_alter_task_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='waypoint',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
