# Generated by Django 5.2.3 on 2025-07-29 19:03

import lbm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('DECORATION', 'Décoration'), ('ICON', 'Icône')], max_length=20)),
                ('file', models.ImageField(upload_to=lbm.models.path_and_rename)),
            ],
        ),
    ]
