# Generated by Django 5.2.3 on 2025-07-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('tip', models.TextField(blank=True)),
            ],
        ),
    ]
