# Generated by Django 5.2.3 on 2025-07-19 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_wizard_vault', '0002_alter_objective_options_alter_objective_api_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objective',
            options={'verbose_name': 'objectif', 'verbose_name_plural': 'objectifs'},
        ),
    ]
