# Generated by Django 5.2.3 on 2025-08-09 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gw2', '0008_alter_item_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_id', models.PositiveIntegerField(blank=True, null=True)),
                ('repeat_achievement_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Bait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.PositiveIntegerField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gw2.item')),
            ],
        ),
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_min', models.PositiveIntegerField(blank=True, null=True)),
                ('power_max', models.PositiveIntegerField(blank=True, null=True)),
                ('bait_any', models.BooleanField()),
                ('specialization', models.CharField(blank=True, choices=[('vindicator', 'Justicier'), ('mechanist', 'Méchamancien'), ('harbinger', 'Augure'), ('specter', 'Spectre'), ('willbender', 'Subjugueur'), ('bladesworn', 'Jurelame'), ('untamed', 'Indomptable'), ('virtuoso', 'Virtuose'), ('catalyst', 'Catalyseur')], max_length=10, null=True)),
                ('strange_diet_achievement', models.BooleanField()),
                ('achievement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gw2_fishing.achievement')),
                ('bait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gw2_fishing.bait')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gw2.item')),
            ],
        ),
        migrations.CreateModel(
            name='FishHole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(blank=True, choices=[('low', 'Faible chance'), ('best', 'Meilleure chance'), ('high', 'Fréquemment repéré')], max_length=5, null=True)),
                ('fish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gw2_fishing.fish')),
                ('hole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gw2_fishing.hole')),
            ],
        ),
    ]
