# Generated by Django 5.2.3 on 2025-08-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_fishing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'verbose_name': 'succès', 'verbose_name_plural': 'succès'},
        ),
        migrations.AlterModelOptions(
            name='bait',
            options={'verbose_name': 'appât', 'verbose_name_plural': 'appâts'},
        ),
        migrations.AlterModelOptions(
            name='fish',
            options={'verbose_name': 'poisson', 'verbose_name_plural': 'poissons'},
        ),
        migrations.AlterModelOptions(
            name='hole',
            options={'verbose_name': 'zone de pêche', 'verbose_name_plural': 'zones de pêche'},
        ),
        migrations.AddField(
            model_name='achievement',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
