# Generated by Django 5.2.3 on 2025-08-09 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_fishing', '0002_alter_achievement_options_alter_bait_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moment', models.CharField(choices=[('tyria_dusk_dawn', 'Aube/Crépuscule [Tyrie centrale]'), ('tyria_day', 'Jour [Tyrie centrale]'), ('tyria_night', 'Nuit [Tyrie centrale]'), ('cantha_dusk_dawn', 'Aube/Crépuscule [Cantha]'), ('canta_day', 'Jour [Cantha]'), ('canta_night', 'Nuit [Cantha]'), ('any', 'Quelconque')], max_length=20)),
                ('frequency', models.CharField(blank=True, choices=[('low', 'Faible chance'), ('best', 'Meilleure chance')], max_length=5, null=True)),
                ('fish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gw2_fishing.fish')),
            ],
        ),
    ]
