# Generated by Django 5.2.3 on 2025-08-09 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_fishing', '0003_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fishhole',
            options={'verbose_name': 'zone de pêche', 'verbose_name_plural': 'zones de pêche'},
        ),
        migrations.AlterModelOptions(
            name='time',
            options={'verbose_name': 'horaire', 'verbose_name_plural': 'horaires'},
        ),
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('arborstone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arborstone', to='gw2_fishing.fish', verbose_name='Pierre Arborea')),
                ('janthir_syntri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='janthir_syntri', to='gw2_fishing.fish', verbose_name='Syntri de Janthir')),
                ('lowland_shore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lowland_shore', to='gw2_fishing.fish', verbose_name='Côte des basses terres')),
                ('mistburned_barrens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistburned_barrens', to='gw2_fishing.fish', verbose_name='Landes de Feu-de-Brume')),
            ],
            options={
                'verbose_name': 'quotidiens',
            },
        ),
    ]
