# Generated by Django 5.2.3 on 2025-08-09 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_fishing', '0004_alter_fishhole_options_alter_time_options_daily'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daily',
            options={'verbose_name': 'quotidiens', 'verbose_name_plural': 'quotidiens'},
        ),
        migrations.AlterField(
            model_name='daily',
            name='arborstone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arborstone', to='gw2_fishing.fish', verbose_name='Pierre Arborea'),
        ),
        migrations.AlterField(
            model_name='daily',
            name='janthir_syntri',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='janthir_syntri', to='gw2_fishing.fish', verbose_name='Syntri de Janthir'),
        ),
        migrations.AlterField(
            model_name='daily',
            name='lowland_shore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lowland_shore', to='gw2_fishing.fish', verbose_name='Côte des basses terres'),
        ),
        migrations.AlterField(
            model_name='daily',
            name='mistburned_barrens',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mistburned_barrens', to='gw2_fishing.fish', verbose_name='Landes de Feu-de-Brume'),
        ),
    ]
