# Generated by Django 5.2.3 on 2025-08-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_fishing', '0005_alter_daily_options_alter_daily_arborstone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='daily_catch',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
