# Generated by Django 5.2.3 on 2025-08-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_fishing', '0006_fish_daily_catch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='moment',
            field=models.CharField(choices=[('tyria_dusk_dawn', 'Aube/Crépuscule [Tyrie centrale]'), ('tyria_day', 'Jour [Tyrie centrale]'), ('tyria_night', 'Nuit [Tyrie centrale]'), ('cantha_dusk_dawn', 'Aube/Crépuscule [Cantha]'), ('cantha_day', 'Jour [Cantha]'), ('cantha_night', 'Nuit [Cantha]'), ('any', 'Quelconque')], max_length=20),
        ),
    ]
